export const hashtags = [
  {
    category: "Tech & Programming",
    tags: [
      "#WebDevelopment",
      "#JavaScript",
      "#ReactJS",
      "#FullStack",
      "#CodingLife",
      "#TechTrends",
      "#ProgrammingTips",
      "#CodeNewbie",
      "#FrontendDev",
      "#BackendDev",
      "#100DaysOfCode",
      "#OpenSource",
    ],
  },
  {
    category: "Design & UX/UI",
    tags: [
      "#UIUX",
      "#DesignInspiration",
      "#UserExperience",
      "#UserInterface",
      "#ProductDesign",
      "#WebDesign",
      "#GraphicDesign",
      "#DesignThinking",
      "#UXResearch",
      "#InteractionDesign",
    ],
  },
  {
    category: "Career & Development",
    tags: [
      "#CareerGrowth",
      "#JobHunt",
      "#TechJobs",
      "#ResumeTips",
      "#InterviewTips",
      "#FreelanceLife",
      "#RemoteWork",
      "#WomenInTech",
      "#TechCommunity",
      "#GrowthMindset",
    ],
  },
  {
    category: "Personal Development",
    tags: [
      "#ProductivityHacks",
      "#Mindfulness",
      "#GoalSetting",
      "#SelfImprovement",
      "#MotivationMonday",
      "#MindsetMatters",
      "#HabitsOfSuccess",
      "#LifeSkills",
      "#TimeManagement",
    ],
  },
  {
    category: "Blogging & Writing",
    tags: [
      "#BloggingTips",
      "#ContentMarketing",
      "#DigitalMarketing",
      "#SEO",
      "#ContentWriting",
      "#BloggersLife",
      "#MarketingStrategies",
      "#SocialMediaMarketing",
      "#Storytelling",
      "#WritingCommunity",
    ],
  },
  {
    category: "Trending & Miscellaneous",
    tags: [
      "#AI",
      "#MachineLearning",
      "#Blockchain",
      "#CyberSecurity",
      "#NFT",
      "#Crypto",
      "#Innovation",
      "#TechNews",
      "#FutureOfWork",
      "#DataScience",
    ],
  },
];
